TrajectoryPlannerROS:
  acc_lim_x: 0.35
  acc_lim_y: 0.0
  acc_lim_theta: 0.8
  max_vel_x: 1.0
  min_vel_x: 0.05
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 0.3

  holonomic_robot: false
  yaw_goal_tolerance: 0.1  # about 5 degrees
  xy_goal_tolerance: 0.1   # 10 cm
  latch_xy_goal_tolerance: true
  
  pdist_scale: 2.0
  gdist_scale: 3.0

  heading_lookahead: 0.325
  heading_scoring: true
  heading_scoring_timestep: 0.8
  meter_scoring: true
  oscillation_reset_dist: 0.05
  occdist_scale: 0.1
  publish_cost_grid_pc: false

  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 3
  vy_samples: 0   # zero for a differential drive robot
  vtheta_samples: 10
  dwa: false
  simple_attractor: false
  