robot_radius: 0.20
#footprint: [[0.17, 0.0], [0.0, 0.17], [0.0, -0.17], [-0.17, 0.0]]
inflation_radius: 0.3

#map_type: costmap
#resolution: 0.025

# The following parameters are only used if map_type is set to "costmap":
#track_unknown_space:    true

# The following parameters are only used if map_type is set to "voxel":
#origin_z:              0.0
#z_resolution:          0.2
#z_voxels:              10
#unknown_threshold:     5
#mark_threshold:        0

observation_sources: base_scan #point_cloud_head_camera

base_scan: {
  data_type:               LaserScan,
  #sensor_frame:            base_laser,
  topic:                   /scan,
  marking:                 true,
  clearing:                true,
  #expected_update_rate:    0.5,
  observation_persistence: 0.0,
  inf_is_valid:            true,
  obstacle_range:          2.5,
  raytrace_range:          3.0,
  min_obstacle_height:     0.10,
  max_obstacle_height:     0.20
  }
  
point_cloud_head_camera: {
#   sensor_frame:            camera_rgb_optical_frame,
   data_type:               PointCloud2,
   topic:                   /camera/depth_registered/points,
   marking:                 true,
   clearing:                true,
   #expected_update_rate:    0.5,
   observation_persistence: 0.0,
   min_obstacle_height:     -0.10,
   max_obstacle_height:     1.5,
   obstacle_range:          2.5,
   raytrace_range:          3.0
   }
